# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DissolveAndClip
                                 A QGIS plugin
 Dissolves a vector file and uses the result to clip a raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-12
        copyright            : (C) 2020 by BNHR
        email                : hi@bnhr.xyz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DissolveAndClip class from file DissolveAndClip.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dissolveandclip import DissolveAndClip
    return DissolveAndClip(iface)
